[env:d1_mini]
platform = espressif8266
board = d1_mini
framework = arduino
monitor_speed = 115200
lib_deps =
    bblanchon/ArduinoJson@^7.1.0
    mobizt/FirebaseClient@^2.0.0
build_flags =
    -DPIO_FRAMEWORK_ARDUINO_MMU_CACHE16_IRAM48
