# PlatformIO pre-script: stamp the firmware with a version string.
#
# Writes src/fw_version_gen.cpp (gitignored) defining kFirmwareVersion, and
# the same string to $BUILD_DIR/fw_version.txt, which
# functions/scripts/publishFirmware.ts reads after building so the manifest
# it publishes can never disagree with the binary it uploads.
#
# Format: YYYY.MM.DD-HHMM-<git sha7>[-dirty], UTC. Sortable as a plain string
# up to the minute — the web UI offers an install only when the published
# version sorts AFTER the running one, so a newer local USB build is not
# shown an "update" that is really a downgrade.
#
# A generated .cpp rather than a -D build flag: a changed define recompiles
# every translation unit, which on this project is minutes per build. Only
# this one file changes, and only when the string does.

import os
import subprocess
from datetime import datetime, timezone

Import("env")  # noqa: F821 — injected by PlatformIO/SCons


def _git(*args):
    try:
        return subprocess.check_output(
            ["git", *args], cwd=env.subst("$PROJECT_DIR"),  # noqa: F821
            stderr=subprocess.DEVNULL).decode().strip()
    except Exception:
        return ""


def _version():
    override = os.environ.get("FW_VERSION")
    if override:
        return override
    sha = _git("rev-parse", "--short=7", "HEAD") or "nogit"
    # Untracked files do not change the image unless they are sources, and
    # the generated file below is gitignored — ignore untracked noise.
    dirty = "-dirty" if _git("status", "--porcelain", "--untracked-files=no") else ""
    stamp = datetime.now(timezone.utc).strftime("%Y.%m.%d-%H%M")
    return f"{stamp}-{sha}{dirty}"


version = _version()
src = os.path.join(env.subst("$PROJECT_SRC_DIR"), "fw_version_gen.cpp")  # noqa: F821
body = (
    "// GENERATED by fw_version.py — do not edit, not tracked.\n"
    '#include "fw_version.h"\n'
    f'const char kFirmwareVersion[] = "{version}";\n'
)
try:
    with open(src) as f:
        current = f.read()
except OSError:
    current = ""
if current != body:
    with open(src, "w") as f:
        f.write(body)

build_dir = env.subst("$BUILD_DIR")  # noqa: F821
os.makedirs(build_dir, exist_ok=True)
with open(os.path.join(build_dir, "fw_version.txt"), "w") as f:
    f.write(version)

print(f"fw_version.py: firmware version {version}")
